layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: nicxes
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: nicxesh
  # unsplash: your_username
  # vk: your_username
  # website: http://nicxes.com
  # youtube: your_username

topics:
  - name: HTML
    web_url: https://github.com/topics/html
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/html/html.png
    
  - name: Pug
    web_url: https://github.com/pugjs/pug
    image_url: https://camo.githubusercontent.com/a43de8ca816e78b1c2666f7696f449b2eeddbeca/68747470733a2f2f63646e2e7261776769742e636f6d2f7075676a732f7075672d6c6f676f2f656563343336636565386664396431373236643738333963626539396431663639343639326330632f5356472f7075672d66696e616c2d6c6f676f2d5f2d636f6c6f75722d3132382e737667
    
  - name: JSX
    web_url: https://github.com/facebook/jsx
    image_url: 
    
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/css/css.png
    
  - name: SASS
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/sass/sass.png

  - name: LESS
    web_url: https://github.com/topics/less
    image_url: https://raw.githubusercontent.com/github/explore/3783a65676ba479267fec803885f070760fee4ac/topics/less/less.png
    
  - name: Boostrap
    web_url: https://github.com/twbs
    image_url: https://avatars1.githubusercontent.com/u/2918581?s=200&v=4
    
  - name: Materialized CSS
    web_url: https://github.com/Dogfalo/materialize
    image_url: https://camo.githubusercontent.com/af195107cec41b655f09ceb0fdb2f205e540b4a4/687474703a2f2f6d6174657269616c697a656373732e636f6d2f7265732f6d6174657269616c697a652e737667
    
  - name: Tailwind CSS
    web_url: https://github.com/tailwindcss
    image_url: https://avatars0.githubusercontent.com/u/30317862?s=200&v=4
    
  - name: Webpack
    web_url: https://github.com/webpack
    image_url: https://avatars1.githubusercontent.com/u/2105791?s=200&v=4
    
  - name: Gulp.js
    web_url: https://github.com/gulpjs
    image_url: https://avatars0.githubusercontent.com/u/6200624?s=200&v=4
    
  - name: Micro
    web_url: https://github.com/zeit/micro
    image_url: https://raw.githubusercontent.com/zeit/art/6451bc300e00312d970527274f316f9b2c07a27e/micro/logo.png
    
  - name: Node.js
    web_url: https://github.com/topics/node
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png
    
  - name: React.js
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png
    
  - name: Zeit
    web_url: https://github.com/topics/zeit
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/zeit/zeit.png

  - name: Heroku
    web_url: https://github.com/heroku
    image_url: https://avatars3.githubusercontent.com/u/23211?s=200&v=4

  - name: Contentful
    web_url: https://github.com/topics/contentful
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/contentful/contentful.png

  - name: Prismic
    web_url: https://prismic.io/
    image_url: https://avatars3.githubusercontent.com/u/4621061?s=200&v=4
    
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Vagrant
    web_url: https://github.com/topics/vagrant
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vagrant/vagrant.png
